### ISSUE TITLE
Add Conda package for windows

### ISSUE THREAD

**Issue by DaveDeCaprio** [closedloop-ai/cv19index#10]
Several people have had problems installing xgboost on windows.  We should provide directions for installing using Anaconda on Windows.  This will be easier than pip.

**Comment by norton-chris** [comment]
Is this still an issue? I was able to install it with "pip install cv19index" after making a new Conda environment and that installed xgboost. I tried doing the same thing on another computer and got a build error with Shap. But following the ReadMe on the install I installed Shap by downloading the whl file and running "pip install shap-0.33.0-cp37-cp37m-win_amd64.whl" and now it works on both my windows computers.

**Comment by DaveDeCaprio** [comment]
I think with the new instructions on the readme we are mostly in good shape.

**Comment by TromNek** [comment]
windows pip install can have a problem 
("ordinal 242 could not be locatedin ....") 
if you have the following dll in your windows\system32 directory;
libiomp5md.dll

rename it to something like;
libiomp5md.dll.badboy

or tell pip to look look there last by setting;
set CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1

I think it's when numpy tries to update.

**Comment by DaveDeCaprio** [comment]
Thanks!

**Comment by ktehseen** [comment]
doesn't look like the download wheel links are active anymore?

**Comment by DaveDeCaprio** [comment]
Sorry about that.  I'll get those fixed.

**Comment by DaveDeCaprio** [comment]
Ok, the links have been updated.
