### ISSUE TITLE
Age cap?

### ISSUE THREAD

**Issue by chesh27** [closedloop-ai/cv19index#12]
Does the model have an intrinsic age cap? We have a population of patients ranging from age 22 to 107. After running the xgboost model using the tutorial, we are seeing all patients aging 98 - 107 with a risk score of only 30, while patients age 92 all have the highest risk score at 73. Our sample sizes are large enough that we would expect to see at least some of the oldest patients in the highest risk category. This made us wonder if there is some kind of intrinsic age cap in the model.

**Comment by DaveDeCaprio** [comment]
Thank you for pointing this out.  I just looked into it and the problem you are seeing is real.  The model doesn't have an intrinsic cap, but I can confirm that the model is producing reduced scores for those above 94.  This is likely an issue with the training data - the outcome is relatively rare and may not have occurred in older individuals by chance.  We are releasing a new model in the next few days and I will make sure to address this then.  Until then, I'd recommend truncating the age at 93.  So anyone who has an age greater than 93, just set it to 93.

**Comment by DaveDeCaprio** [comment]
This has been addressed int he latest model.  We have retrained and no longer see this issue.  Also, the new model works on ages 18 and up.
