### ISSUE TITLE
Gender label mapping

### ISSUE THREAD

**Issue by chrislauinger4** [closedloop-ai/cv19index#13]
What is the mapping of gender label (1/2) to Male/Female? 
 
I only see numeric values for gender in the example and couldn't find relevant mappings in this repo: https://github.com/closedloop-ai/cv19index/blob/master/examples/data/demographics.csv

**Comment by DaveDeCaprio** [comment]
There is actually an issue int he current example data.  
Female should be 0
Male should be 1

(It is not 1 and 2 as listed int he data).

**Comment by DaveDeCaprio** [comment]
The new preprocessing code included with version 1.1 allows either the strings male/female or an integer where 0 is female and 1 is male.
