### ISSUE TITLE
urllib.parse.quote: improper usage?

### ISSUE THREAD

**Issue by kdrobnyh** [closedloop-ai/cv19index#28]
I got a problem running the model:
`ValueError: feature_names mismatch`

The problem is that df_inputs in predict.py:253 has columns with wrong names, like 

> Diagnosis%20of%20Nephritis_%20nephrosis_%20renal%20sclerosis%20in%20the%20previous%2012%20months

This is because of use urllib.parse.quote here:
`df_inputs.columns = [urllib.parse.quote(col) for col in df_inputs.columns]`

Python 3.7.7 and 3.8.1, Windows 10.

**Comment by DaveDeCaprio** [comment]
I think I might know what this is.  Are you using the "xgboost" model rather than "xgboost_all_ages"? 

We'd suggest using the "xgboost_all_ages" model as a workaround until we can get that addressed.  The all ages model generally has better performance anyway.

**Comment by kdrobnyh** [comment]
Yes, I wanted to use different models. So you use different feature names?

**Comment by DaveDeCaprio** [comment]
I just pushed an update that fixes this issue for the xgboost model.  It is the same columns.  The all ages model uses a newer version of our platform that urlencodes the columns.

**Comment by kdrobnyh** [comment]
Great, thank you!
