### ISSUE TITLE
Error with reorder_inputs

### ISSUE THREAD

**Issue by 2miatran** [closedloop-ai/cv19index#35]
Hello, 
I tried running the prediction as followed, and got this error. This seems to be because model["model"].feature_names is empty, resulting in the 'NoneType' error in the reorder_inputs function. Can you please help fix it? Thank you.

```   input_fpath = "data/all_input_ri.csv"
    input_schema = resource_filename("cv19index", "resources/xgboost/input.csv.schema.json")
    model = resource_filename("cv19index", "resources/xgboost/model.pickle")
    model = resource_filename("cv19index", "resources/model_simple/model.pickle")

    asOfDate = '2020-01-31'
    fclaim = "data/claim_test.csv"
    fdemo = "data/demo_test.csv"
    output = "data/prediction_test.csv"
    model_name = "xgboost"

    do_run_claims(fdemo, fclaim, output, model_name, asOfDate, feature_file = None)
```

Traceback (most recent call last):

  File "<ipython-input-131-3316ea1ce244>", line 12, in <module>
    do_run_claims(fdemo, fclaim, output, model_name, asOfDate, feature_file = None)

  File "C:\Users\..\Python\Python37\site-packages\cv19index\predict.py", line 431, in do_run_claims
    predictions = run_xgb_model(input_df, model, quote = quote)

  File "C:\Users\..\Python\Python37\site-packages\cv19index\predict.py", line 359, in run_xgb_model
    df_inputs = reorder_inputs(df_inputs, predictor)

  File "C:\Users\..\Python\Python37\site-packages\cv19index\predict.py", line 342, in reorder_inputs
    if set(predictor["model"].feature_names) == set(df_inputs.columns) and predictor[

TypeError: 'NoneType' object is not iterable

```from pkg_resources import resource_filename
from cv19index.io import read_model

model_name = "xgboost"
schema_fpath = resource_filename("cv19index", f"resources/{model_name}/input.csv.schema.json")
model_fpath = resource_filename("cv19index",f"resources/{model_name}/model.pickle")
model = read_model(model_fpath)

print(f'model["model"].feature_names: {model["model"].feature_names}')
```
Output:
model["model"].feature_names: None

Version: 
cv19index: 1.1.4
xgboost: 1.4.0

**Comment by DaveDeCaprio** [comment]
Hmm, I'm running that code and the values are working correctly.  There are two possible problems.  The first is that xgboost has a change in version 1.4.0 where it isn't reading in the feature names correctly.  

We did all our testing with xgboost 1.0.2.  You could try that xgboost version.

The other problem might be that you aren't reading in the right pickle file.  Check the path returned by resource_filename and make sure it points to the same file that is checked in.

**Comment by 2miatran** [comment]
Thanks Dave for the prompt response. Turned out there was an older version of xgboost (could not be removed due to denied permission) that caused the "_AttributeError: function 'XGBoosterUnserializeFromBuffer' not found"_ even when switching to xgboost 1.0.2. Creating a separate env and installing xgboost 1.0.2 works for me. Just leave comments here for anyone have similar issues. Thanks again!

**Comment by DaveDeCaprio** [comment]
Thanks, glad we got it working for you.
