### ISSUE TITLE
A script to get ROC AUC results without cv19index package

### ISSUE THREAD

**Issue by ogencoglu** [closedloop-ai/cv19index#4]
It would be great if you can just provide an end-to-end working **python script** that simply outputs the ROC AUC on the data you have in this repo. This way people can quickly replace their models with your xgboost model and try new things out.

Requiring _cv19index_ to be installed as a package should not be needed as we are really fighting against time as humanity.

**Comment by DaveDeCaprio** [comment]
There isn't a requirement to install it as a package.  We provide that as an option, but you can just run this code.

We are making improvements as fast as we can.  Would appreciate any help you can give in putting together that script.

**Comment by DaveDeCaprio** [comment]
Also, unfortunately, we can't open source the data we used to train the model due to privacy constraints.  We provide some example data to help people integrate the model, but that is synthetic data that won't provide realistic accuracy numbers.

**Comment by DaveDeCaprio** [comment]
The new 1.1.0 release does contain a run_cv19index.py script that people can use to run the model without having to install from PyPI.
