### ISSUE TITLE
Share data! 

### ISSUE THREAD

**Issue by Cerebrock** [closedloop-ai/cv19index#7]
:angry:

**Comment by DaveDeCaprio** [comment]
The data we are using to build this index is the 2015-2016 CMS Limited Data Set files.  You can find more information on these files at https://www.cms.gov/Research-Statistics-Data-and-Systems/Files-for-Order/LimitedDataSets

Our data use agreement with CMS does not allow us to share this data externally, although we are allowed to make the research based on this data publicly available.  CMS has these restrictions in place to protect the privacy of the Medicare beneficiaries contained in this data set.

Anyone can apply to CMS to purchase this data for research use.  If anyone has the data we are happy to provide more detail on exactly what we did to build the index.
